name: Smart Review Revoker | PR

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

run-name: ${{ github.event.pull_request.title }} | ${{ github.event.pull_request.number }} | Safe check

on:
  pull_request:
    branches:
      - main

jobs:
  check-if-changes-are-safe:
    runs-on: ubuntu-latest
    name: Safe check
    steps:
      - name: Download Previously Approved Commit ID
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: save-pr-approved-commit-sha.yml
          workflow_conclusion: success
          search_artifacts: true
          name: approved-commit-id-${{github.event.pull_request.number}}
          if_no_artifact_found: warn

      - shell: bash
        run: |
          value=`cat approved-commit-id.txt`
          echo Approved commit id $value
          echo "Current head sha: ${{ github.event.pull_request.head.sha }}"
          echo "Current head red: ${{ github.event.pull_request.head.ref }}"
          echo "APPROVED_COMMIT_ID=$value" >> $GITHUB_ENV
      - run: echo ${{ env.APPROVED_COMMIT_ID }}

      - name: 'Fetch PR comment count'
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_ENV}"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: "${{ env.APPROVED_COMMIT_ID }}"
          path: old-code

      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.PR_FETCH_DEPTH }}
          ref: "${{ github.event.pull_request.head.sha }}"
          path: new-code

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v32
        with:
          json: true
          path: new-code
          base_sha: ${{ env.APPROVED_COMMIT_ID }}
          sha: ${{ github.event.pull_request.head.sha }}
      
      - name: Safe modification check
        id: safe-modification-check
        uses: anikrajc/test-file-safe-check-action@v6
        with:
          old-code: old-code
          new-code: new-code
          all-changed-files: "{ \"added_files\":${{ steps.changed-files.outputs.added_files }}, \"copied_files\":${{ steps.changed-files.outputs.copied_files }}, \"deleted_files\":${{ steps.changed-files.outputs.deleted_files }}, \"modified_files\":${{ steps.changed-files.outputs.modified_files }}, \"renamed_files\":${{ steps.changed-files.outputs.renamed_files }}, \"type_changed_files\":${{ steps.changed-files.outputs.type_changed_files }}, \"unmerged_files\":${{ steps.changed-files.outputs.unmerged_files }}, \"unknown_files\":${{ steps.changed-files.outputs.unknown_files }} }"
          ignore-list: "[]"
          start-marker: "test-srr-start"
          end-marker: "test-srr-end"

      - name: Send comments
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: '${{github.event.pull_request.number}}',
              owner: '${{github.event.repository.owner.login}}',
              repo: '${{github.event.repository.name}}',
              body: '🤖 SRR : Changes were safe = ${{ steps.safe-modification-check.outputs.is-safe-change }}'
            })
