name: Smart Review Revoker | PR

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

run-name: ${{ github.event.pull_request.title }} | ${{ github.event.pull_request.number }}

on:
  pull_request:
    branches:
      - main

jobs:

  check-if-pr-commit-is-dirty:
    runs-on: ubuntu-latest
    name: Print all commits
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: save-pr-approved-commit-sha.yml
          workflow_conclusion: success
          search_artifacts: true
          name: approved-commit-id-${{github.event.pull_request.number}}
          if_no_artifact_found: warn
      # - name: Download Previously Approved Commit ID
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: approved-commit-id
      - shell: bash
        run: |
          value=`cat approved-commit-id.txt`
          echo Approved commit id $value
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 2
      - name: Another step
        run: |
          echo "head_ref: ${{ github.head_ref }}"
          echo "Sha: ${{ github.sha }}"
          echo "PR head Sha: ${{ github.event.pull_request.head.sha }}"



      # - name: Get changed files using defaults
      #   id: changed-files
      #   uses: tj-actions/changed-files@v32
      # - name: List all added files
      #   run: |
      #     for file in ${{ steps.changed-files.outputs.added_files }}; do
      #       echo "$file was added"
      #     done
      # - name: Run step when a file modified
      #   run: |
      #     for file in ${{ steps.changed-files.outputs.modified_files }}; do
      #       echo "$file was modified"
      #     done
      # - name: Run step when a file deleted
      #   run: |
      #     for file in ${{ steps.changed-files.outputs.deleted_files }}; do
      #       echo "$file was deleted"
      #     done
